# 1. Прописать в `source` расположение папки с БД и файлами на хост машине.
# 2. docker compose up -d
# 3. docker compose run migrate

version: '3.7'

x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-debug}
  
services:
  app:
    image: np:latest
    build:
      context: .
    environment:
      <<: *shared_environment
    volumes:
      - type: bind
        source: /Users/borisovodov/Data
        target: /np/Data
    ports:
      - '8080:8080'
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]
  migrate:
    image: np:latest
    build:
      context: .
    environment:
      <<: *shared_environment
    volumes:
      - type: bind
        source: /Users/borisovodov/Data
        target: /np/Data
    command: ["migrate", "--yes"]
    deploy:
      replicas: 0
  revert:
    image: np:latest
    build:
      context: .
    environment:
      <<: *shared_environment
    volumes:
      - type: bind
        source: /Users/borisovodov/Data
        target: /np/Data
    command: ["migrate", "--revert", "--yes"]
    deploy:
      replicas: 0
