version: '3'

services:
  db:
    image: postgres:11.2
    expose:
      - 5432
    volumes:
      - pg_data:/var/lib/postgresql/data
      - pg_backups:/pg_backups
  web:
    image: borisovodov/np
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pg_data: {}
  pg_backups: {}
