# 1. Прописать в `source` расположение папки с БД и файлами на хост машине. // TODO: эта строчка уйдёт в будущем, когда прикручу работу с volumes.
# 2. docker compose up -d
# 3. docker compose run migrate

version: '3.7'

x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-debug}
  MAPBOX_ACCESS_KEY: MAPBOX_ACCESS_KEY
  
services:
  app:
    image: borisovodov/np:latest
    environment:
      <<: *shared_environment
    volumes:
      - type: bind
        source: /root/Data
        target: /np/Data
    ports:
      - "8080:8080"
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]
  migrate:
    image: borisovodov/np:latest
    environment:
      <<: *shared_environment
    volumes:
      - type: bind
        source: /root/Data
        target: /np/Data
    command: ["migrate", "--yes"]
    deploy:
      replicas: 0
  revert:
    image: borisovodov/np:latest
    environment:
      <<: *shared_environment
    volumes:
      - type: bind
        source: /root/Data
        target: /np/Data
    command: ["migrate", "--revert", "--yes"]
    deploy:
      replicas: 0
  caddy:
    image: caddy:2.8.4
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
#      - /site:/np
      - caddy_data:/data
      - caddy_config:/config
volumes:
  caddy_data:
#    external: true
  caddy_config:
