# 1. `ufw allow http`
# 2. `ufw allow https`
# 3. `git clone https://github.com/borisovodov/np.git`
# 4. `docker compose up -d`
# 5. `docker compose run migrate -y`
# 6. Удалить всё докерное: `docker system prune -y`.

version: '3.7'

x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-debug}
  
services:
  app:
    image: borisovodov/np:latest
    environment:
      <<: *shared_environment
    volumes:
      - db:/np/Data
    ports:
      - "8080:8080"
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]
  migrate:
    image: borisovodov/np:latest
    environment:
      <<: *shared_environment
    volumes:
      - db:/np/Data
    command: ["migrate", "--yes"]
    deploy:
      replicas: 0
  revert:
    image: borisovodov/np:latest
    environment:
      <<: *shared_environment
    volumes:
      - db:/np/Data
    command: ["migrate", "--revert", "--yes"]
    deploy:
      replicas: 0
  caddy:
    image: caddy:2.8.4
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
volumes:
  caddy_data:
  caddy_config:
  db:
